### ISSUE TITLE
problem cloning submodule

### ISSUE THREAD

**Issue by sabolton** [bevesce/SublimeTodoflow#2]
Using the installation command given in the readme, I get the error "fatal: Could not read from remote repository. Please make sure you have the correct access rights." This happens on both Windows 7 and macOS 10.12

It looks like the recursive cloning cannot access the submodule because it is protected.

**Comment by bevesce** [comment]
I have no idea why but cloning with submodules over ssh seems to be broken somehow. I've changed the command and submodule path to use https. It seems to work this way.

So you can use:
`git clone --recursive https://github.com/bevesce/todoflow_sublime.git path/to/Sublime Text 3/Packages/SublimeTodoflow`
