### ISSUE TITLE
Date search not working

### ISSUE THREAD

**Issue by eenpadvinder** [bevesce/SublimeTodoflow#4]
I've added a search for today like this, but nothing happens:

```
Today @search(@today union @due <[d] tomorrow)
Test @search(@due <[d] tomorrow)
```

Should it?

**Comment by eenpadvinder** [comment]
It appears it's not about the date, but about < 
```
Today @search(@today union @due = [d] today)
```
works just fine!

**Comment by bevesce** [comment]
I've updated todoflow dependency, it should work now
